import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { Provider } from "@/chakra/provider";
import "./globals.css";
import Header from "@/components/layout/Header";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ubuntu.className} antialiased`}
      >
        <Provider>  
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
